<?php

namespace App\Filament\Resources\Product\ProductCollectionsResource\Pages;

use App\Filament\Resources\Product\ProductCollectionsResource;
use App\Helper\StringHelper;
use Filament\Actions;
use Filament\Resources\Pages\CreateRecord;

class CreateProductCollections extends CreateRecord
{
    protected static string $resource = ProductCollectionsResource::class;

    protected function mutateFormDataBeforeCreate(array $data): array
    {
        $data['slug'] = StringHelper::generateSlug($data['name']);
        return parent::mutateFormDataBeforeCreate($data); // TODO: Change the autogenerated stub
    }
}
