<?php

namespace App\Filament\Resources\Ecom\OrderResource\Pages;

use App\Filament\Resources\Ecom\OrderResource;
use App\Models\Ecom\Address;
use Filament\Actions;
use Filament\Resources\Pages\EditRecord;

class EditOrder extends EditRecord
{
    protected static string $resource = OrderResource::class;

    protected function getHeaderActions(): array
    {
        return [
            Actions\DeleteAction::make(),
        ];
    }

    protected function mutateFormDataBeforeFill(array $data): array
    {
        $shippingAddress = Address::find($data['shipping_address_id']);

        if ($shippingAddress instanceof Address) {
            $array = $shippingAddress->toArray();
            foreach ($array as $key => $value) $data['shipping_' . $key] = $value;
        }

        $array = null;
        $billingAddress = Address::find($data['billing_address_id']);

        if ($billingAddress instanceof Address) {
            $array = $billingAddress->toArray();
            foreach ($array as $key => $value) $data['billing_' . $key] = $value;
        }

        return parent::mutateFormDataBeforeFill($data); // TODO: Change the autogenerated stub
    }
}
